version: "3.8"

services:
  db:
    image: postgres
    ports:
      - 57001:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - system_design_sql:/data/db
    user: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - system_design_sql:/data/db

volumes:
  system_design_sql:
