version: "3.8"

services:
  db:
    image: postgres
    ports:
      - 57001:5432
    environment:
      - POSTGRES_USER=flleonx
      - POSTGRES_PASSWORD=flleonxpass
    volumes:
      - golang_sql:/data/db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

volumes:
  golang_sql:
